@api-key = ea2fa8ffa4d7e03729e551eee17d3ccf
@lang = jp

@hirakue-zip = 311-4144

# forcast api
https://api.openweathermap.org/data/2.5/forecast?zip={{hirakue-zip}},JP&appid={{api-key}}&lang={{lang}}

###

# current weather api
https://api.openweathermap.org/data/2.5/weather?zip={{hirakue-zip}},JP&appid={{api-key}}&lang={{lang}}
